intranet/apps/api/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url

from .views import api_root
from ..announcements import api as announcements_api
from ..eighth.views import api as eighth_api
from ..emerg import api as emerg_api
from ..schedule import api as schedule_api
from ..users import api as users_api

urlpatterns = [
    url(r"^$", api_root, name="api_root"),
    url(r"^/announcements$", announcements_api.ListCreateAnnouncement.as_view(), name="api_announcements_list_create"),
    url(r"^/announcements/(?P<pk>[0-9]+)$", announcements_api.RetrieveUpdateDestroyAnnouncement.as_view(), name="api_announcements_detail"),
    url(r"^/blocks$", eighth_api.EighthBlockList.as_view(), name="api_eighth_block_list"),
    url(r"^/blocks/(?P<pk>[0-9]+)$", eighth_api.EighthBlockDetail.as_view(), name="api_eighth_block_detail"),
    url(r"^/search/(?P<query>.+)$", users_api.Search.as_view(), name="api_user_search"),
    url(r"^/activities$", eighth_api.EighthActivityList.as_view(), name="api_eighth_activity_list"),
    url(r"^/activities/(?P<pk>[0-9]+)$", eighth_api.EighthActivityDetail.as_view(), name="api_eighth_activity_detail"),
    url(r"^/profile$", users_api.ProfileDetail.as_view(), name="api_user_myprofile_detail"),
    url(r"^/profile/(?P<pk>[0-9]+)$", users_api.ProfileDetail.as_view(), name="api_user_profile_detail"),
    url(r"^/profile/(?P<username>[A-Za-z0-9]+)$", users_api.ProfileDetail.as_view(), name="api_user_profile_detail_by_username"),
    url(r"^/profile/(?P<pk>[0-9]+)/picture$", users_api.ProfilePictureDetail.as_view(), name="api_user_profile_picture_default"),
    url(r"^/profile/(?P<username>[A-Za-z0-9]+)/picture$", users_api.ProfilePictureDetail.as_view(),
        name="api_user_profile_picture_default_by_username"),
    url(r"^/profile/(?P<pk>[0-9]+)/picture/(?P<photo_year>[a-zA-Z]+)$", users_api.ProfilePictureDetail.as_view(), name="api_user_profile_picture"),
    url(r"^/profile/(?P<username>[A-Za-z0-9]+)/picture/(?P<photo_year>[a-zA-Z]+)$", users_api.ProfilePictureDetail.as_view(),
        name="api_user_profile_picture_by_username"),
    url(r"^/signups/user$", eighth_api.EighthUserSignupListAdd.as_view(), name="api_eighth_user_signup_list_myid"),
    url(r"^/signups/user/(?P<user_id>[0-9]+)$", eighth_api.EighthUserSignupListAdd.as_view(), name="api_eighth_user_signup_list"),
    url(r"^/signups/user/favorites$", eighth_api.EighthUserFavoritesListToggle.as_view(), name="api_eighth_user_favorites_list_myid"),
    url(r"^/signups/scheduled_activity/(?P<scheduled_activity_id>[0-9]+)$", eighth_api.EighthScheduledActivitySignupList.as_view(),
        name="api_eighth_scheduled_activity_signup_list"),
    url(r"^/schedule$", schedule_api.DayList.as_view(), name="api_schedule_day_list"),
    url(r"^/schedule/(?P<date>.*)$", schedule_api.DayDetail.as_view(), name="api_schedule_day_detail"),
    url(r"^/emerg$", emerg_api.emerg_status, name="api_emerg_status"),
]

intranet/apps/bus/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from . import views

urlpatterns = [
    url(r"^$", views.home, name="bus"),
]

intranet/urls.py
# -*- coding: utf-8 -*-

from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic.base import RedirectView, TemplateView

from intranet.apps.oauth.views import ApplicationUpdateView
from intranet.apps.error.views import (handle_404_view, handle_500_view, handle_503_view)

admin.autodiscover()

admin.site.site_header = "Ion administration"  # type: ignore

urlpatterns = [
    url(r"^favicon\.ico$", RedirectView.as_view(url="/static/img/favicon.ico"), name="favicon"),
    url(r"^robots\.txt$", TemplateView.as_view(template_name="robots.txt", content_type="text/plain"), name="robots"),
    url(r"^manifest\.json$", RedirectView.as_view(url="/static/manifest.json"), name="chrome_manifest"),
    url(r"^serviceworker\.js$", TemplateView.as_view(template_name="serviceworker.js", content_type="text/javascript"), name="chrome_serviceworker"),
    url(r"^api", include("intranet.apps.api.urls"), name="api_root"),
    url(r"^", include("intranet.apps.auth.urls")),
    url(r"^announcements", include("intranet.apps.announcements.urls")),
    url(r"^eighth", include("intranet.apps.eighth.urls")),
    url(r"^events", include("intranet.apps.events.urls")),
    url(r"^files", include("intranet.apps.files.urls")),
    url(r"^groups", include("intranet.apps.groups.urls")),
    url(r"^polls", include("intranet.apps.polls.urls")),
    url(r"^search", include("intranet.apps.search.urls")),
    url(r"^profile", include("intranet.apps.users.urls")),
    url(r"^schedule", include("intranet.apps.schedule.urls")),
    url(r"^seniors", include("intranet.apps.seniors.urls")),
    url(r"^preferences", include("intranet.apps.preferences.urls")),
    url(r"^feedback", include("intranet.apps.feedback.urls")),
    url(r"^welcome", include("intranet.apps.welcome.urls")),
    url(r"^notifications", include("intranet.apps.notifications.urls")),
    url(r"^signage", include("intranet.apps.signage.urls")),
    url(r"^printing", include("intranet.apps.printing.urls")),
    url(r"^bus", include("intranet.apps.bus.urls")),
    url(r"^itemreg", include("intranet.apps.itemreg.urls")),
    url(r"^lostfound", include("intranet.apps.lostfound.urls")),
    url(r"^emailfwd", include("intranet.apps.emailfwd.urls")),
    url(r"^parking", include("intranet.apps.parking.urls")),
    url(r"^djangoadmin/doc/", include('django.contrib.admindocs.urls')),
    # FIXME: update when admin supports django 1.10+ properly
    url(r"^djangoadmin/", admin.site.urls),
    url(r"^oauth/applications/(?P<pk>\d+)/update/$", ApplicationUpdateView.as_view()),
    url(r"^oauth/", include(("oauth2_provider.urls", "oauth2_provider"))),
    url(r"^oauth/$", RedirectView.as_view(url="/oauth/applications/"), name="oauth_redirect"),
    url(r"^nominations", include("intranet.apps.nomination.urls")),
    url(r"^courses", include("intranet.apps.users.class_urls")),
]

if settings.SHOW_DEBUG_TOOLBAR:
    import debug_toolbar

    urlpatterns += [url(r"^__debug__/", include(debug_toolbar.urls))]  # type: ignore

handler404 = handle_404_view
handler500 = handle_500_view
handler503 = handle_503_view  # maintenance mode

intranet/utils/urls.py
# -*- coding: utf-8 -*-

from urllib import parse


def add_get_parameters(url, parameters, percent_encode=True):
    """Utility function to add GET parameters to an existing URL.

    Args:
        parameters
            A dictionary of the parameters that should be added.
        percent_encode
            Whether the query parameters should be percent encoded.

    Returns:
        The updated URL.

    """
    url_parts = list(parse.urlparse(url))
    query = dict(parse.parse_qs(url_parts[4]))
    query.update(parameters)

    if percent_encode:
        url_parts[4] = parse.urlencode(query)
    else:
        url_parts[4] = "&".join([key + "=" + value for key, value in query.items()])

    return parse.urlunparse(url_parts)

intranet/apps/bus/models.py
from django.db import models


class Route(models.Model):
    """A bus route (e.g. TJ-24)"""

    ARRIVAL_STATUSES = (('a', 'Arrived (In the lot)'), ('d', 'Delayed'), ('o', 'On Time (Expected)'))

    route_name = models.CharField(max_length=30, unique=True)
    space = models.CharField(max_length=4, blank=True)
    bus_number = models.CharField(max_length=5, blank=True)
    status = models.CharField('arrival status', choices=ARRIVAL_STATUSES, max_length=1, default='o')

    def reset_status(self):
        """Reset status to (on time) """
        self.status = 'o'
        self.space = ''
        self.save()

intranet/apps/users/models.py
# -*- coding: utf-8 -*-

import logging
from datetime import datetime
from dateutil.relativedelta import relativedelta
from base64 import b64encode

from django.conf import settings
from django.contrib.auth.models import AbstractBaseUser, AnonymousUser, PermissionsMixin, UserManager as DjangoUserManager
from django.core.cache import cache
from django.db import models
from django.db.models import Count
from django.utils import timezone
from django.utils.functional import cached_property

from intranet.middleware import threadlocals

from ..groups.models import Group
from ..preferences.fields import PhoneField
from ..bus.models import Route

logger = logging.getLogger(__name__)

# TODO: this is disgusting
GRADE_NUMBERS = ((9, 'freshman'), (10, 'sophomore'), (11, 'junior'), (12, 'senior'), (13, 'staff'))


class UserManager(DjangoUserManager):
    """User model Manager for table-level User queries.

    Provides table-level LDAP abstraction for the User model. If a call
    to a method fails for this Manager, the call is deferred to the
    default User model manager.

    """

    def user_with_student_id(self, student_id):
        """Get a unique user object by FCPS student ID. (Ex. 1624472)"""
        results = User.objects.filter(student_id=student_id)
        if len(results) == 1:
            return results.first()
        return None

    def user_with_ion_id(self, student_id):
        """Get a unique user object by Ion ID. (Ex. 489)"""
        if isinstance(student_id, str) and not student_id.isdigit():
            return None
        results = User.objects.filter(id=student_id)
        if len(results) == 1:
            return results.first()
        return None

    def users_in_year(self, year):
        """Get a list of users in a specific graduation year."""
        return User.objects.filter(graduation_year=year)

    def user_with_name(self, given_name=None, sn=None):
        """Get a unique user object by given name (first/nickname and last)."""
        results = []

        if sn and not given_name:
            results = User.objects.filter(last_name=sn)
        elif given_name:
            query = {'first_name': given_name}
            if sn:
                query['last_name'] = sn
            results = User.objects.filter(**query)

            if len(results) == 0:
                # Try their first name as a nickname
                del query['first_name']
                query['nickname'] = given_name
                results = User.objects.filter(**query)

        if len(results) == 1:
            return results.first()

        return None

    def users_with_birthday(self, month, day):
        """Return a list of user objects who have a birthday on a given date."""

        users = User.objects.filter(properties___birthday__month=month, properties___birthday__day=day)
        results = []
        print('=============================')
        for user in users:
            # TODO: permissions system
            print(user.first_name)
            results.append(user)

        return results

    # Simple way to filter out teachers and students without hitting LDAP.
    # This shouldn't be a problem unless the username scheme changes and
    # the consequences of error are not significant.

    def get_students(self):
        """Get user objects that are students (quickly)."""
        return User.objects.filter(user_type="student", graduation_year__gte=settings.SENIOR_GRADUATION_YEAR)

    def get_teachers(self):
        """Get user objects that are teachers (quickly)."""
        users = User.objects.filter(user_type="teacher")
        extra = [9996, 8888, 7011]
        users = users.exclude(id__in=extra)
        # Add possible exceptions handling here
        users = users | User.objects.filter(id__in=[31863, 32327, 32103, 33228])

        return users

    def get_teachers_sorted(self):
        """Get teachers sorted by last name.

        This is used for the announcement request page.

        """
        teachers = self.get_teachers()
        teachers = [(u.last_name, u.first_name, u.id) for u in teachers]
        for t in teachers:
            if t is None or t[0] is None or t[1] is None or t[2] is None:
                teachers.remove(t)
        for t in teachers:
            if t[0] is None or len(t[0]) <= 1:
                teachers.remove(t)
        teachers.sort(key=lambda u: (u[0], u[1]))
        # Hack to return QuerySet in given order
        id_list = [t[2] for t in teachers]
        clauses = ' '.join(['WHEN id=%s THEN %s' % (pk, i) for i, pk in enumerate(id_list)])
        ordering = 'CASE %s END' % clauses
        queryset = User.objects.filter(id__in=id_list).extra(select={'ordering': ordering}, order_by=('ordering',))
        return queryset


class User(AbstractBaseUser, PermissionsMixin):
    """Django User model subclass
    """
    TITLES = (('Mr.', 'Mr.'), ('Ms.', 'Ms.'), ('Mrs.', 'Mrs.'), ('Dr.', 'Dr.'))

    USER_TYPES = (
        ('student', 'Student'),
        ('teacher', 'Teacher'),
        ('counselor', 'Counselor'),
        ('user', 'Attendance-Only User'),
        ('simple_user', 'Simple User'),
        ('tjstar_presenter', 'tjStar Presenter'),
        ('alum', 'Alumnus'),
        ('service', 'Service Account'),
    )

    TITLES = (('mr', 'Mr.'), ('ms', 'Ms.'), ('mrs', 'Mrs.'), ('dr', 'Dr.'))
    # Django Model Fields
    username = models.CharField(max_length=30, unique=True)

    # See Email model for emails
    # See Phone model for phone numbers
    # See Website model for websites

    user_locked = models.BooleanField(default=False)

    # Local internal fields
    first_login = models.DateTimeField(null=True)
    seen_welcome = models.BooleanField(default=False)

    # Local preference fields
    receive_news_emails = models.BooleanField(default=False)
    receive_eighth_emails = models.BooleanField(default=False)

    receive_schedule_notifications = models.BooleanField(default=False)

    student_id = models.CharField(max_length=settings.FCPS_STUDENT_ID_LENGTH, unique=True, null=True)
    user_type = models.CharField(max_length=30, choices=USER_TYPES, default='student')
    admin_comments = models.TextField(blank=True, null=True)
    counselor = models.ForeignKey('self', on_delete=models.SET_NULL, related_name='students', null=True)
    graduation_year = models.IntegerField(null=True)
    title = models.CharField(max_length=5, choices=TITLES, null=True, blank=True)
    first_name = models.CharField(max_length=35, null=True)
    middle_name = models.CharField(max_length=70, null=True)
    last_name = models.CharField(max_length=70, null=True)
    nickname = models.CharField(max_length=35, null=True)
    gender = models.NullBooleanField()
    preferred_photo = models.OneToOneField('Photo', related_name='+', null=True, blank=True, on_delete=models.SET_NULL)
    primary_email = models.OneToOneField('Email', related_name='+', null=True, blank=True, on_delete=models.SET_NULL)
    bus_route = models.ForeignKey(Route, on_delete=models.SET_NULL, null=True)

    # Required to replace the default Django User model
    USERNAME_FIELD = "username"
    """Override default Model Manager (objects) with
    custom UserManager to add table-level functionality."""
    objects = UserManager()

    @staticmethod
    def get_signage_user():
        return User(id=99999)

    @property
    def address(self):
        return self.properties.address

    @property
    def birthday(self):
        return self.properties.birthday

    @property
    def schedule(self):
        return self.properties.schedule

    def member_of(self, group):
        """Returns whether a user is a member of a certain group.

        Args:
            group
                The name of a group (string) or a group object

        Returns:
            Boolean

        """
        if isinstance(group, Group):
            group = group.name
        return self.groups.filter(name=group).exists()

    def has_admin_permission(self, perm):
        """Returns whether a user has an admin permission (explicitly, or implied by being in the
        "admin_all" group)

        Returns:
            Boolean

        """
        return self.member_of("admin_all") or self.member_of("admin_" + perm)

    @property
    def full_name(self):
        """Return full name, e.g. Angela William.

        This is required for subclasses of User.

        """
        return "{} {}".format(self.first_name, self.last_name)

    @property
    def display_name(self):
        return self.full_name

    @property
    def last_first(self):
        """Return a name in the format of:
            Lastname, Firstname [(Nickname)]
        """
        return "{}, {} ".format(self.last_name, self.first_name) + ("({})".format(self.nickname) if self.nickname else "")

    @property
    def last_first_id(self):
        """Return a name in the format of:
            Lastname, Firstname [(Nickname)] (Student ID/ID/Username)
        """
        return ("{}{} ".format(self.last_name, ", " + self.first_name if self.first_name else "") + ("({}) ".format(self.nickname)
                                                                                                     if self.nickname else "") +
                ("({})".format(self.student_id if self.is_student and self.student_id else self.username)))

    @property
    def last_first_initial(self):
        """Return a name in the format of:
            Lastname, F [(Nickname)]
        """
        return ("{}{} ".format(self.last_name, ", " + self.first_name[:1] + "." if self.first_name else "") + ("({}) ".format(self.nickname)
                                                                                                               if self.nickname else ""))

    @property
    def short_name(self):
        """Return short name (first name) of a user.

        This is required for subclasses of User.

        """
        return self.first_name

    def get_short_name(self):

intranet/templates/bus/home.html
{% extends "page_with_nav.html" %}
{% load static %}
{% load svg %}
{% load pipeline %}

{% block title %}
    {{ block.super }} - Bus
{% endblock %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/selectize.js-0.12.4/dist/css/selectize.default.css' %}" />
    {{ block.super }}
    {% stylesheet 'bus' %}
    {% stylesheet 'polls' %}
    {% stylesheet 'dashboard' %}
{% endblock %}

{% block js %}
    {{ block.super }}
    <script type="text/javascript">
        window.firstname = "{{ request.user.first_name }}";
        window.isAdmin = {{ admin | yesno:"true,false" }};
        window.isStudent = {{ request.user.is_student | yesno:"true,false" }}
        window.enableBusDriver = {{ enable_bus_driver | yesno:"true,false" }}
        window.label_status_strings = {
            "a": {
                empty_text: "No buses have arrived yet.",
                name: "Arrived",
                personal: "already here!"
            },
            "o": {
                empty_text: "All buses have arrived or are delayed.",
                name: "On Time",
                personal: "on time."
            },
            "d": {
                empty_text: "No delays.",
                name: "Delayed",
                personal: "delayed. 😢"
            },
        };
    </script>
    <script type="text/javascript" src="{% static 'js/vendor/reconnecting-websocket.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/vendor/svg.min.js' %}"></script>
    {% if enable_bus_driver %}
    <script src='https://api.tiles.mapbox.com/mapbox-gl-js/v0.44.1/mapbox-gl.js'></script>
    <link href='https://api.tiles.mapbox.com/mapbox-gl-js/v0.44.1/mapbox-gl.css' rel='stylesheet' />
    {% endif %}
    <script type="text/javascript" src="{% static 'vendor/selectize.js-0.12.4/dist/js/standalone/selectize.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bus.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/vendor/underscore-min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/vendor/backbone-min.js' %}"></script>
{% endblock %}

{% block main %}
    {% verbatim %}
    <script type="text/template" id="personal-status">
        <% if (route_name !== "Empty route") { %>
            <h2 class="personal-status bordered-element">Hi <%= firstname %>, your bus (<strong><%= route_name %></strong>) is <%= label_status_strings[status].personal %> Have a great day!</h2>
        <% } else { %>
        {% endverbatim %}
            <h2 class="personal-status bordered-element">It looks like you don't have a bus registered. <a href="{% url 'preferences' %}#id_bus_route" target="_blank">Register.</a></h2>
        {% verbatim %}
        <% } %>
    </script>
    <script type="text/template" id="route-view">
        <span class="route-name"><%= route_name %></span>
        <br>
        <% if (bus_number) { %>
            <span class="bus-number"> #<%= bus_number %> </span>
        <% } else { %>
            <span class="bus-number"> No bus number recorded. </span>
        <% } %>
        <% if (isAdmin) { %>
            <select name="status" id="<%= id %>">
                <% for (var key in label_status_strings) { %>
                    <option value="<%= key %>" <% if (key === status) print("selected") %>> <%= label_status_strings[key].name %> </option>
                <% } %>
            </select>
        <% } %>
    </script>
    <script type="text/template" id="status-group-view">
        <% console.log(name, empty_text, collection)%>
        <h2 class="status"> <%= name %> </h2>
        <% if (collection.length === 0) { %>
            <h3 class="empty"> <%= empty_text %> </h3>
        <% } %>
    </script>
    <script type="text/template" id="action-button-view">
        <div class="action-button">
            <i class="fa <%= icon %>"></i><span class="action-button-text"> <%= text %></span>
        </div>
    </script>
    <script type="text/template" id="search-widget-view">
        <div class="search-widget">
            <i class="back-button fa fa-arrow-left"></i><select name="buses" id="buses"></select>
        </div>
    </script>
    {% endverbatim %}
    <script type="text/template" id="map-view">
        {% if enable_bus_driver %}
        <div id='map' class='busdriver-map'></div>
        <div id='bd-bus' class='busdriver-bus'></div>
        {% endif %}
        {% svg 'optimized_bus_map_v2' %}
    </script>
    <div class="primary-content">
        {% comment %}
        <div class="beta-warning bordered-element">
            Looking for Ion BusDriver? Click on a bus space, then click "skrt skrt".
        </div>
        {% endcomment %}
        <div class="info"> </div>
    </div>
{% endblock %}