intranet/apps/api/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url

from .views import api_root
from ..announcements import api as announcements_api
from ..eighth.views import api as eighth_api
from ..emerg import api as emerg_api
from ..schedule import api as schedule_api
from ..users import api as users_api

urlpatterns = [
    url(r"^$", api_root, name="api_root"),
    url(r"^/announcements$", announcements_api.ListCreateAnnouncement.as_view(), name="api_announcements_list_create"),
    url(r"^/announcements/(?P<pk>[0-9]+)$", announcements_api.RetrieveUpdateDestroyAnnouncement.as_view(), name="api_announcements_detail"),
    url(r"^/blocks$", eighth_api.EighthBlockList.as_view(), name="api_eighth_block_list"),
    url(r"^/blocks/(?P<pk>[0-9]+)$", eighth_api.EighthBlockDetail.as_view(), name="api_eighth_block_detail"),
    url(r"^/search/(?P<query>.+)$", users_api.Search.as_view(), name="api_user_search"),
    url(r"^/activities$", eighth_api.EighthActivityList.as_view(), name="api_eighth_activity_list"),
    url(r"^/activities/(?P<pk>[0-9]+)$", eighth_api.EighthActivityDetail.as_view(), name="api_eighth_activity_detail"),
    url(r"^/profile$", users_api.ProfileDetail.as_view(), name="api_user_myprofile_detail"),
    url(r"^/profile/(?P<pk>[0-9]+)$", users_api.ProfileDetail.as_view(), name="api_user_profile_detail"),
    url(r"^/profile/(?P<username>[A-Za-z0-9]+)$", users_api.ProfileDetail.as_view(), name="api_user_profile_detail_by_username"),
    url(r"^/profile/(?P<pk>[0-9]+)/picture$", users_api.ProfilePictureDetail.as_view(), name="api_user_profile_picture_default"),
    url(r"^/profile/(?P<username>[A-Za-z0-9]+)/picture$", users_api.ProfilePictureDetail.as_view(),
        name="api_user_profile_picture_default_by_username"),
    url(r"^/profile/(?P<pk>[0-9]+)/picture/(?P<photo_year>[a-zA-Z]+)$", users_api.ProfilePictureDetail.as_view(), name="api_user_profile_picture"),
    url(r"^/profile/(?P<username>[A-Za-z0-9]+)/picture/(?P<photo_year>[a-zA-Z]+)$", users_api.ProfilePictureDetail.as_view(),
        name="api_user_profile_picture_by_username"),
    url(r"^/signups/user$", eighth_api.EighthUserSignupListAdd.as_view(), name="api_eighth_user_signup_list_myid"),
    url(r"^/signups/user/(?P<user_id>[0-9]+)$", eighth_api.EighthUserSignupListAdd.as_view(), name="api_eighth_user_signup_list"),
    url(r"^/signups/user/favorites$", eighth_api.EighthUserFavoritesListToggle.as_view(), name="api_eighth_user_favorites_list_myid"),
    url(r"^/signups/scheduled_activity/(?P<scheduled_activity_id>[0-9]+)$", eighth_api.EighthScheduledActivitySignupList.as_view(),
        name="api_eighth_scheduled_activity_signup_list"),
    url(r"^/schedule$", schedule_api.DayList.as_view(), name="api_schedule_day_list"),
    url(r"^/schedule/(?P<date>.*)$", schedule_api.DayDetail.as_view(), name="api_schedule_day_detail"),
    url(r"^/emerg$", emerg_api.emerg_status, name="api_emerg_status"),
]

intranet/apps/bus/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from . import views

urlpatterns = [
    url(r"^$", views.home, name="bus"),
]

intranet/urls.py
# -*- coding: utf-8 -*-

from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic.base import RedirectView, TemplateView

from intranet.apps.oauth.views import ApplicationUpdateView
from intranet.apps.error.views import (handle_404_view, handle_500_view, handle_503_view)

admin.autodiscover()

admin.site.site_header = "Ion administration"  # type: ignore

urlpatterns = [
    url(r"^favicon\.ico$", RedirectView.as_view(url="/static/img/favicon.ico"), name="favicon"),
    url(r"^robots\.txt$", TemplateView.as_view(template_name="robots.txt", content_type="text/plain"), name="robots"),
    url(r"^manifest\.json$", RedirectView.as_view(url="/static/manifest.json"), name="chrome_manifest"),
    url(r"^serviceworker\.js$", TemplateView.as_view(template_name="serviceworker.js", content_type="text/javascript"), name="chrome_serviceworker"),
    url(r"^api", include("intranet.apps.api.urls"), name="api_root"),
    url(r"^", include("intranet.apps.auth.urls")),
    url(r"^announcements", include("intranet.apps.announcements.urls")),
    url(r"^eighth", include("intranet.apps.eighth.urls")),
    url(r"^events", include("intranet.apps.events.urls")),
    url(r"^files", include("intranet.apps.files.urls")),
    url(r"^groups", include("intranet.apps.groups.urls")),
    url(r"^polls", include("intranet.apps.polls.urls")),
    url(r"^search", include("intranet.apps.search.urls")),
    url(r"^profile", include("intranet.apps.users.urls")),
    url(r"^schedule", include("intranet.apps.schedule.urls")),
    url(r"^seniors", include("intranet.apps.seniors.urls")),
    url(r"^preferences", include("intranet.apps.preferences.urls")),
    url(r"^feedback", include("intranet.apps.feedback.urls")),
    url(r"^welcome", include("intranet.apps.welcome.urls")),
    url(r"^notifications", include("intranet.apps.notifications.urls")),
    url(r"^signage", include("intranet.apps.signage.urls")),
    url(r"^printing", include("intranet.apps.printing.urls")),
    url(r"^bus", include("intranet.apps.bus.urls")),
    url(r"^itemreg", include("intranet.apps.itemreg.urls")),
    url(r"^lostfound", include("intranet.apps.lostfound.urls")),
    url(r"^emailfwd", include("intranet.apps.emailfwd.urls")),
    url(r"^parking", include("intranet.apps.parking.urls")),
    url(r"^djangoadmin/doc/", include('django.contrib.admindocs.urls')),
    # FIXME: update when admin supports django 1.10+ properly
    url(r"^djangoadmin/", admin.site.urls),
    url(r"^oauth/applications/(?P<pk>\d+)/update/$", ApplicationUpdateView.as_view()),
    url(r"^oauth/", include(("oauth2_provider.urls", "oauth2_provider"))),
    url(r"^oauth/$", RedirectView.as_view(url="/oauth/applications/"), name="oauth_redirect"),
    url(r"^nominations", include("intranet.apps.nomination.urls")),
    url(r"^courses", include("intranet.apps.users.class_urls")),
]

if settings.SHOW_DEBUG_TOOLBAR:
    import debug_toolbar

    urlpatterns += [url(r"^__debug__/", include(debug_toolbar.urls))]  # type: ignore

handler404 = handle_404_view
handler500 = handle_500_view
handler503 = handle_503_view  # maintenance mode

intranet/utils/urls.py
# -*- coding: utf-8 -*-

from urllib import parse


def add_get_parameters(url, parameters, percent_encode=True):
    """Utility function to add GET parameters to an existing URL.

    Args:
        parameters
            A dictionary of the parameters that should be added.
        percent_encode
            Whether the query parameters should be percent encoded.

    Returns:
        The updated URL.

    """
    url_parts = list(parse.urlparse(url))
    query = dict(parse.parse_qs(url_parts[4]))
    query.update(parameters)

    if percent_encode:
        url_parts[4] = parse.urlencode(query)
    else:
        url_parts[4] = "&".join([key + "=" + value for key, value in query.items()])

    return parse.urlunparse(url_parts)

intranet/apps/bus/models.py
from django.db import models


class Route(models.Model):
    """A bus route (e.g. TJ-24)"""

    ARRIVAL_STATUSES = (('a', 'Arrived (In the lot)'), ('d', 'Delayed'), ('o', 'On Time (Expected)'))

    route_name = models.CharField(max_length=30, unique=True)
    space = models.CharField(max_length=4, blank=True)
    bus_number = models.CharField(max_length=5, blank=True)
    status = models.CharField('arrival status', choices=ARRIVAL_STATUSES, max_length=1, default='o')

    def reset_status(self):
        """Reset status to (on time) """
        self.status = 'o'
        self.space = ''
        self.save()

intranet/apps/emailfwd/models.py
# -*- coding: utf-8 -*-
from django.db import models
from ..users.models import User


class SeniorEmailForward(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    email = models.EmailField()

    def __str__(self):
        return "{}".format(self.user)

intranet/apps/feedback/models.py
# -*- coding: utf-8 -*-
from django.db import models

from ..users.models import User


class Feedback(models.Model):
    user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    comments = models.CharField(max_length=50000)
    date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-date"]

    def __str__(self):
        return "{} - {}".format(self.user, self.date)

intranet/apps/files/models.py
# -*- coding: utf-8 -*-

from django.contrib.auth.models import Group as DjangoGroup
from django.db import models
from django.db.models import Manager, Q
"""
    Sample TJ configuration:

        Host.objects.create(name="Computer Systems Lab",
                            code="csl",
                            address="remote.tjhsst.edu",
                            linux=True)

        afs = Host.objects.create(name="CSL AFS Root",
                                  code="afs",
                                  address="remote.tjhsst.edu",
                                  directory="/afs/csl/",
                                  linux=True,
                                  available_to_all=True)

        afs.groups_visible.add(Group.objects.get(name="admin_all"))

        Host.objects.create(name="Home Folder (M)",
                            code="tj03_m",
                            address="tj03.local.tjhsst.edu",
                            directory="{win}",
                            windows=True)

        Host.objects.create(name="Resources Drive (R)",
                            code="tj03_r",
                            address="tj03.local.tjhsst.edu",
                            directory="/R/",
                            windows=True)

        Host.objects.create(name="Windows Root",
                            code="win",
                            address="tj03.local.tjhsst.edu",
                            windows=True)

"""


class HostManager(Manager):

    def visible_to_user(self, user):
        """Get a list of hosts available to a given user.

        Same logic as Announcements and Events.

        """

        return Host.objects.filter(Q(groups_visible__in=user.groups.all()) | Q(groups_visible__isnull=True)).distinct()


class Host(models.Model):
    objects = HostManager()

    name = models.CharField(max_length=255)
    code = models.CharField(max_length=32)
    address = models.CharField(max_length=255)
    directory = models.CharField(max_length=255, blank=True)

    windows = models.BooleanField(default=False)
    linux = models.BooleanField(default=False)

    groups_visible = models.ManyToManyField(DjangoGroup, blank=True)

    available_to_all = models.BooleanField(default=False)

    def visible_to(self, user):
        if self.groups_visible.count() == 0:
            return True
        return (self in Host.objects.visible_to_user(user))

    def __str__(self):
        return "{} ({})".format(self.name, self.code)

    class Meta:
        ordering = ["-linux", "name"]

intranet/apps/groups/models.py
# -*- coding: utf-8 -*-

from django.contrib.auth import models as auth_models
from django.db import models


class GroupManager(auth_models.GroupManager):
    """This GroupManager model is really just the default Django
    django.contrib.auth.models.GroupManager, just with an extra method."""

    def student_visible(self):
        """Return a list of groups that are student-visible.
        """
        group_ids = set()
        for group in Group.objects.all():
            if group.properties.student_visible:
                group_ids.add(group.id)

        return Group.objects.filter(id__in=group_ids)


class Group(auth_models.Group):
    """ This Group model is really just the default Django
        django.contrib.auth.models.Group, but with a "properties"
        property which returns or creates the GroupProperties field
        for that group. Because GroupProperties objects are only created
        here when they are first accessed, and not on creation or edit,
        you must *always* access them directly through the Group object,
        and not through GroupProperties.

        This presents some complications. All model-level relationships for
        a group should use the *Django contrib.auth.models.Group object*, and
        not the custom one defined here. You will see this done, to avoid
        confusion, like:

            from django.contrib.auth.models import Group as DjangoGroup

        with DjangoGroup being referenced in the OneToOne or ManyToMany relationship.

        e.x.:
            Group.objects.get(id=9).properties.student_visible
    """

    objects = GroupManager()

    @property
    def properties(self):
        try:
            props = self.groupproperties
        except GroupProperties.DoesNotExist:
            props, created = GroupProperties.objects.get_or_create(group=self)

        return props

    class Meta:
        proxy = True


class GroupProperties(models.Model):
    """ The GroupProperties model contains a OneToOneField with the
        intranet.apps.groups.models.Group object (really just the default
        django.contrib.auth.models.Group), and contains properties and other
        app-specific options about a group.

        group
            A OneToOneField with a Group object.
        student_visible
            Whether the group should be visible to students in group selections.

    """
    group = models.OneToOneField(Group, on_delete=models.CASCADE)
    student_visible = models.BooleanField(default=False)

    def __str__(self):
        return "{}".format(self.group)

intranet/apps/lostfound/models.py
# -*- coding: utf-8 -*-
from django.db import models
from ..users.models import User


class LostItem(models.Model):
    user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    title = models.CharField(max_length=100)
    description = models.TextField(max_length=1000)
    last_seen = models.DateField()
    added = models.DateTimeField(auto_now_add=True)
    found = models.BooleanField(default=False)

    def __str__(self):
        return "{}".format(self.title)

    class Meta:
        ordering = ["-added"]


class FoundItem(models.Model):
    user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    title = models.CharField(max_length=100)
    description = models.TextField(max_length=1000)
    found = models.DateField()
    added = models.DateTimeField(auto_now_add=True)
    retrieved = models.BooleanField(default=False)

    def __str__(self):
        return "{}".format(self.title)

    class Meta:
        ordering = ["-added"]

intranet/apps/seniors/models.py
# -*- coding: utf-8 -*-

from django.conf import settings
from django.db import models

from ..users.models import User


class College(models.Model):
    name = models.CharField(max_length=1000)
    ceeb = models.IntegerField(unique=True)

    def __str__(self):
        return "{} ({})".format(self.name, self.ceeb)

    class Meta:
        ordering = ["name"]


class SeniorManager(models.Manager):

    def filled(self):
        return Senior.objects.exclude(college=None, major=None).filter(user__graduation_year=settings.SENIOR_GRADUATION_YEAR)


class Senior(models.Model):
    objects = SeniorManager()
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    college = models.ForeignKey(College, blank=True, null=True, on_delete=models.CASCADE)
    MAJORS = [
        "Computer Science", "Engineering", "Education", "Mathematics", "Physics", "Biology", "Chemistry", "Geology", "History", "Literature",
        "English", "Other", "Language", "Drama/Theater", "Undecided", "Music", "Political Science", "Neuroscience", "Business", "Economics",
        "Communications", "World Studies", "Art/Art History", "Biochemistry", "Computer Engineering", "Anthropology", "Film", "Atmospheric Science",
        "Astronomy", "Psychology", "Genetics", "Social Work", "Architecture", "Public Policy", "Classics", "Marine Biology", "Dance", "Philosophy",
        "Emergency Health Services", "Animal Science", "Computer and Video Imaging", "Geography", "International Relations", "Foreign Service",
        "Broadcast Journalism", "Semitic Studies", "Microbiology", "Finance", "Journalism", "Aeronautics/Astronautics", "Pre-med", "Pre-law",
        "Automotive Technician", "Computer Game Design", "Petroleum Engineering", "American Studies", "African-American Studies", "Linguistics",
        "Sociology", "International Finance", "Public Policy in Science and Technology", "Information Technology", "Network Engineering",
        "Environmental Science", "Evolutionary Biology", "Advertising", "Apparel Design", "East Asian Studies", "Biomedical Engineering",
        "Policy Analysis and Management", "Videogame Design and Development", "Electrical Engineering", "Information Systems", "Theatre",
        "Theatre/Directing", "Leadership", "Design", "Environmental Thought and Practice", "Athletic Training", "Physical Therapy",
        "Chemical Engineering", "Athletic Training & Physical Therapy", "Civil Engineering", "Industrial and Labor Relations", "Bowling Management",
        "Pre-Dental", "Aerospace Engineering", "French", "German", "Spanish", "Italian", "Chinese", "Operations Research",
        "Game Design and Development", "Software Engineering", "International Development", "Mechanical Engineering", "Mathematics & Computer Science"
    ]
    major = models.CharField(max_length=100, choices=[(i, i) for i in MAJORS] + [('', 'Undecided')], blank=True, null=True)
    college_sure = models.BooleanField(default=False)
    major_sure = models.BooleanField(default=False)

    def __str__(self):
        return "{}".format(self.user)

    class Meta:
        ordering = ["user"]

intranet/templates/seniors/add.html
{% extends "page_with_nav.html" %}
{% load static %}
{% load pipeline %}

{% block title %}
    {{ block.super }} - Seniors
{% endblock %}

{% block css %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/selectize.js-0.12.4/dist/css/selectize.default.css' %}" />
    {% stylesheet 'dashboard' %}
    <style type="text/css">
    #id_college, #id_major {
        width: 500px;
    }

    form.senior-form .selectize-control {
        display: inline;
    }

    form.senior-form .selectize-input {
        width: 500px;
    }
    </style>
{% endblock %}

{% block js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'vendor/selectize.js-0.12.4/dist/js/standalone/selectize.min.js' %}"></script>
    <script type="text/javascript">
    $(function() {
        $("#id_college, #id_major").selectize();
    });
    </script>
{% endblock %}

{% block main %}
    <div class="primary-content polls">
        <h2>Add Destination Info</h2>

        <div class="seniors-container">
            <form action="" method="post" name="senior-form" class="senior-form">
                {% csrf_token %}
                <table>
                    {{ form.as_table }}
                    <tr>
                        <td colspan="2">
                            <input type="submit" value="Update Info" />
                        </td>
                    </tr>
                </table>
            </form>
        </div>
    </div>

    </div>
{% endblock %}

intranet/templates/seniors/home.html
{% extends "page_with_nav.html" %}
{% load static %}
{% load pipeline %}


{% block title %}
    {{ block.super }} - Seniors
{% endblock %}

{% block css %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/sortable-0.8.0/css/sortable-theme-minimal.css' %}" />
    {% stylesheet 'dashboard' %}
    <style type="text/css">
    td.unsure {
        font-style: italic;
    }
    </style>
{% endblock %}

{% block js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'vendor/sortable-0.8.0/js/sortable.min.js' %}"></script>
    <script type="text/javascript">
    </script>
{% endblock %}

{% block main %}
    <div class="primary-content polls">
        <h2>Senior Destinations</h2>
        <div class="button-container">
            {% if is_senior %}
                <a href="{% url 'seniors_add' %}" class="button">
                    {% if own_senior %}Modify{% else %}Add{% endif %} Your Destination Info
                </a>
            {% endif %}
        </div>
        <br />
        <b>{{ seniors|length }} senior{{ seniors|length|pluralize }} have added destinations.</b>
        <br />
        <div class="seniors-container">
            <table class="seniors-table fancy-table" data-sortable>
                <thead>
                    <tr>
                        <th>Student</th>
                        <th>College</th>
                        <th>Major</th>
                    </tr>
                </thead>
                <tbody>
                {% for senior in seniors %}
                    <tr>
                        <td data-value="{{ senior.user.last_name }} {{ senior.user.first_name }}">
                            <a href="{% url 'user_profile' senior.user.id %}">
                                {{ senior.user.full_name }}
                            </a>
                        </td>
                        <td class="{% if not senior.college_sure %}un{% endif %}sure">
                            {{ senior.college }}
                            {% if not senior.college_sure %} (unsure){% endif %}
                        </td>
                        <td class="{% if not senior.major_sure %}un{% endif %}sure">
                            {{ senior.major }}
                            {% if not senior.major_sure %} (unsure){% endif %}
                        </td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="3">No seniors have entered destination info.</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

    </div>
{% endblock %}

intranet/templates/seniors/login.html
{% load pipeline %}
{% load static %}
{% stylesheet 'dashboard.widgets' %}
<script>
graduated = function() {
    $("body").css({
        "background-image": "url(https://raw.githubusercontent.com/tjcsl/iodine/master/www/gc/winner.jpg)",
        "background-size": "400px"
    });
    //$('<div style=" position: fixed; top: 0; left: 50%; margin-left: -202px; width: 406px; height: 100%; background: rgba(242,242,242,0.8); z-index: -1"></div>').appendTo($("body"));
}
</script>
<script src="{% static 'js/dashboard/seniors.js' %}"></script>
<style>
.widget.seniors-widget {
    width: 400px;
    margin-left: -100px;
    margin-top: 25px;
    border-color: #0048ab;
    display: block !important;
}
@media (max-width: 404px) {
    .widget.seniors-widget {
        width: 300px;
        margin-left: -50px;
    }
}
</style>
<div class="widget extra-widget seniors-widget" data-graduation-date="{{ senior_graduation }}" data-graduation-year="{{ senior_graduation_year }}" style="">
<div class="widget-title" style="border-color: #0048ab">
<h2>
Seniors: Class of 2016
</h2>
<div class="info">

</div>
</div>
<div class="widget-content">
<center><span class="seniors-clock"></span></center>
</div>
</div>

intranet/templates/seniors/login_top.html
<style>body { background: #0048ab; }</style>
<div style=" position: fixed; top: 0; left: 50%; margin-left: -202px; width: 406px; height: 100%; background: rgba(242,242,242,0.8); z-index: -1"></div>
<iframe scrolling="no" src="https://tjhsst.edu/~2016jwoglom/canvastext?" style="width:100%;height:50%;position:fixed;top:0;left:0;overflow:hidden;z-index:-2"></iframe>

intranet/templates/seniors/signage.html
<style>body { background: #0048ab; }</style>
<div style=" position: fixed; top: 0; {% if landscape %} left: 75%; {% else %}left: 50%;{% endif %} margin-left: -202px; width: 406px; height: 100%; background: rgba(242,242,242,0.8); z-index: -1"></div>
<iframe src="https://tjhsst.edu/~2016jwoglom/canvastext?" style="width:100%;height:50%;position:fixed;top:0;left:0;z-index:-2"></iframe>