intranet/apps/api/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url

from .views import api_root
from ..announcements import api as announcements_api
from ..eighth.views import api as eighth_api
from ..emerg import api as emerg_api
from ..schedule import api as schedule_api
from ..users import api as users_api

urlpatterns = [
    url(r"^$", api_root, name="api_root"),
    url(r"^/announcements$", announcements_api.ListCreateAnnouncement.as_view(), name="api_announcements_list_create"),
    url(r"^/announcements/(?P<pk>[0-9]+)$", announcements_api.RetrieveUpdateDestroyAnnouncement.as_view(), name="api_announcements_detail"),
    url(r"^/blocks$", eighth_api.EighthBlockList.as_view(), name="api_eighth_block_list"),
    url(r"^/blocks/(?P<pk>[0-9]+)$", eighth_api.EighthBlockDetail.as_view(), name="api_eighth_block_detail"),
    url(r"^/search/(?P<query>.+)$", users_api.Search.as_view(), name="api_user_search"),
    url(r"^/activities$", eighth_api.EighthActivityList.as_view(), name="api_eighth_activity_list"),
    url(r"^/activities/(?P<pk>[0-9]+)$", eighth_api.EighthActivityDetail.as_view(), name="api_eighth_activity_detail"),
    url(r"^/profile$", users_api.ProfileDetail.as_view(), name="api_user_myprofile_detail"),
    url(r"^/profile/(?P<pk>[0-9]+)$", users_api.ProfileDetail.as_view(), name="api_user_profile_detail"),
    url(r"^/profile/(?P<username>[A-Za-z0-9]+)$", users_api.ProfileDetail.as_view(), name="api_user_profile_detail_by_username"),
    url(r"^/profile/(?P<pk>[0-9]+)/picture$", users_api.ProfilePictureDetail.as_view(), name="api_user_profile_picture_default"),
    url(r"^/profile/(?P<username>[A-Za-z0-9]+)/picture$", users_api.ProfilePictureDetail.as_view(),
        name="api_user_profile_picture_default_by_username"),
    url(r"^/profile/(?P<pk>[0-9]+)/picture/(?P<photo_year>[a-zA-Z]+)$", users_api.ProfilePictureDetail.as_view(), name="api_user_profile_picture"),
    url(r"^/profile/(?P<username>[A-Za-z0-9]+)/picture/(?P<photo_year>[a-zA-Z]+)$", users_api.ProfilePictureDetail.as_view(),
        name="api_user_profile_picture_by_username"),
    url(r"^/signups/user$", eighth_api.EighthUserSignupListAdd.as_view(), name="api_eighth_user_signup_list_myid"),
    url(r"^/signups/user/(?P<user_id>[0-9]+)$", eighth_api.EighthUserSignupListAdd.as_view(), name="api_eighth_user_signup_list"),
    url(r"^/signups/user/favorites$", eighth_api.EighthUserFavoritesListToggle.as_view(), name="api_eighth_user_favorites_list_myid"),
    url(r"^/signups/scheduled_activity/(?P<scheduled_activity_id>[0-9]+)$", eighth_api.EighthScheduledActivitySignupList.as_view(),
        name="api_eighth_scheduled_activity_signup_list"),
    url(r"^/schedule$", schedule_api.DayList.as_view(), name="api_schedule_day_list"),
    url(r"^/schedule/(?P<date>.*)$", schedule_api.DayDetail.as_view(), name="api_schedule_day_detail"),
    url(r"^/emerg$", emerg_api.emerg_status, name="api_emerg_status"),
]

intranet/apps/bus/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from . import views

urlpatterns = [
    url(r"^$", views.home, name="bus"),
]

intranet/urls.py
# -*- coding: utf-8 -*-

from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic.base import RedirectView, TemplateView

from intranet.apps.oauth.views import ApplicationUpdateView
from intranet.apps.error.views import (handle_404_view, handle_500_view, handle_503_view)

admin.autodiscover()

admin.site.site_header = "Ion administration"  # type: ignore

urlpatterns = [
    url(r"^favicon\.ico$", RedirectView.as_view(url="/static/img/favicon.ico"), name="favicon"),
    url(r"^robots\.txt$", TemplateView.as_view(template_name="robots.txt", content_type="text/plain"), name="robots"),
    url(r"^manifest\.json$", RedirectView.as_view(url="/static/manifest.json"), name="chrome_manifest"),
    url(r"^serviceworker\.js$", TemplateView.as_view(template_name="serviceworker.js", content_type="text/javascript"), name="chrome_serviceworker"),
    url(r"^api", include("intranet.apps.api.urls"), name="api_root"),
    url(r"^", include("intranet.apps.auth.urls")),
    url(r"^announcements", include("intranet.apps.announcements.urls")),
    url(r"^eighth", include("intranet.apps.eighth.urls")),
    url(r"^events", include("intranet.apps.events.urls")),
    url(r"^files", include("intranet.apps.files.urls")),
    url(r"^groups", include("intranet.apps.groups.urls")),
    url(r"^polls", include("intranet.apps.polls.urls")),
    url(r"^search", include("intranet.apps.search.urls")),
    url(r"^profile", include("intranet.apps.users.urls")),
    url(r"^schedule", include("intranet.apps.schedule.urls")),
    url(r"^seniors", include("intranet.apps.seniors.urls")),
    url(r"^preferences", include("intranet.apps.preferences.urls")),
    url(r"^feedback", include("intranet.apps.feedback.urls")),
    url(r"^welcome", include("intranet.apps.welcome.urls")),
    url(r"^notifications", include("intranet.apps.notifications.urls")),
    url(r"^signage", include("intranet.apps.signage.urls")),
    url(r"^printing", include("intranet.apps.printing.urls")),
    url(r"^bus", include("intranet.apps.bus.urls")),
    url(r"^itemreg", include("intranet.apps.itemreg.urls")),
    url(r"^lostfound", include("intranet.apps.lostfound.urls")),
    url(r"^emailfwd", include("intranet.apps.emailfwd.urls")),
    url(r"^parking", include("intranet.apps.parking.urls")),
    url(r"^djangoadmin/doc/", include('django.contrib.admindocs.urls')),
    # FIXME: update when admin supports django 1.10+ properly
    url(r"^djangoadmin/", admin.site.urls),
    url(r"^oauth/applications/(?P<pk>\d+)/update/$", ApplicationUpdateView.as_view()),
    url(r"^oauth/", include(("oauth2_provider.urls", "oauth2_provider"))),
    url(r"^oauth/$", RedirectView.as_view(url="/oauth/applications/"), name="oauth_redirect"),
    url(r"^nominations", include("intranet.apps.nomination.urls")),
    url(r"^courses", include("intranet.apps.users.class_urls")),
]

if settings.SHOW_DEBUG_TOOLBAR:
    import debug_toolbar

    urlpatterns += [url(r"^__debug__/", include(debug_toolbar.urls))]  # type: ignore

handler404 = handle_404_view
handler500 = handle_500_view
handler503 = handle_503_view  # maintenance mode

intranet/utils/urls.py
# -*- coding: utf-8 -*-

from urllib import parse


def add_get_parameters(url, parameters, percent_encode=True):
    """Utility function to add GET parameters to an existing URL.

    Args:
        parameters
            A dictionary of the parameters that should be added.
        percent_encode
            Whether the query parameters should be percent encoded.

    Returns:
        The updated URL.

    """
    url_parts = list(parse.urlparse(url))
    query = dict(parse.parse_qs(url_parts[4]))
    query.update(parameters)

    if percent_encode:
        url_parts[4] = parse.urlencode(query)
    else:
        url_parts[4] = "&".join([key + "=" + value for key, value in query.items()])

    return parse.urlunparse(url_parts)

intranet/apps/bus/models.py
from django.db import models


class Route(models.Model):
    """A bus route (e.g. TJ-24)"""

    ARRIVAL_STATUSES = (('a', 'Arrived (In the lot)'), ('d', 'Delayed'), ('o', 'On Time (Expected)'))

    route_name = models.CharField(max_length=30, unique=True)
    space = models.CharField(max_length=4, blank=True)
    bus_number = models.CharField(max_length=5, blank=True)
    status = models.CharField('arrival status', choices=ARRIVAL_STATUSES, max_length=1, default='o')

    def reset_status(self):
        """Reset status to (on time) """
        self.status = 'o'
        self.space = ''
        self.save()

intranet/apps/eighth/models.py
# -*- coding: utf-8 -*-
import datetime
import logging
from itertools import chain

from django.conf import settings
from django.contrib.auth.models import Group as DjangoGroup
from django.core.cache import cache
from django.core.exceptions import NON_FIELD_ERRORS, ValidationError
from simple_history.models import HistoricalRecords
from django.db import models, transaction
from django.db.models import Manager, Q, Count
from django.utils import formats

from . import exceptions as eighth_exceptions
from ..notifications.emails import email_send
from ..users.models import User
from ...utils.date import is_current_year, get_date_range_this_year
from ...utils.deletion import set_historical_user

logger = logging.getLogger(__name__)


class AbstractBaseEighthModel(models.Model):
    """Abstract base model that includes created and last modified times."""

    created_time = models.DateTimeField(auto_now_add=True, null=True)
    last_modified_time = models.DateTimeField(auto_now=True, null=True)

    class Meta:
        abstract = True


class EighthSponsor(AbstractBaseEighthModel):
    """Represents a sponsor for an eighth period activity.

    A sponsor could be linked to an actual user or just a name.

    Attributes:
        first_name
            The first name of the sponsor
        last_name
            The last name of the sponsor
        user
            A :class:`users.User` object
            linked to the sponsor.
        online_attendance
            Whether the sponsor takes attendance online.
        contracted_eighth
            Whether the sponsor is contracted to supervise 8th periods.
        show_full_name
            Whether to always show the sponsor's full name
            (e.x. because there are two teachers named Lewis)

    """

    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    user = models.OneToOneField(User, null=True, blank=True, on_delete=set_historical_user)
    online_attendance = models.BooleanField(default=True)
    contracted_eighth = models.BooleanField(default=True)
    show_full_name = models.BooleanField(default=False)

    history = HistoricalRecords()

    class Meta:
        unique_together = (("first_name", "last_name", "user", "online_attendance"),)
        ordering = (
            "last_name",
            "first_name",
        )

    @property
    def name(self):
        if self.show_full_name and self.first_name:
            return self.last_name + ", " + self.first_name
        else:
            return self.last_name

    @property
    def to_be_assigned(self):
        return sum([x in self.name.lower() for x in ["to be assigned", "to be determined", "to be announced"]])

    def __str__(self):
        return self.name


class EighthRoom(AbstractBaseEighthModel):
    """Represents a room in which an eighth period activity can be held.

    Attributes:
        name
            The name of the room.
        capacity
            The maximum capacity of the room (-1 for unlimited, 0 to prevent student signup)

    """
    name = models.CharField(max_length=100)
    capacity = models.SmallIntegerField(default=28)
    available_for_eighth = models.BooleanField(default=True)

    history = HistoricalRecords()

    unique_together = (("name", "capacity"),)

    @classmethod
    def total_capacity_of_rooms(cls, rooms):
        capacity = 0
        for r in rooms:
            c = r.capacity
            if c == -1:
                return -1
            else:
                capacity += c
        return capacity

    @property
    def formatted_name(self):
        if self.name[0].isdigit():  # All rooms starting with an integer will be prefixed
            return "Rm. {}".format(self.name)
        if self.name.startswith('Room'):  # Some room names are prefixed with 'Room'; for consistency
            return "Rm. {}".format(self.name[5:])
        if self.name.startswith('Weyanoke'):
            return "Wey. {}".format(self.name[9:])
        return self.name

    @property
    def to_be_determined(self):
        return sum([x in self.name.lower() for x in ["to be assigned", "to be determined", "to be announced"]])

    def __str__(self):
        return "{} ({})".format(self.name, self.capacity)
        # return "{}".format(self.name)

    class Meta:
        ordering = ("name",)


class EighthActivityExcludeDeletedManager(models.Manager):

    def get_queryset(self):
        return (super(EighthActivityExcludeDeletedManager, self).get_queryset().exclude(deleted=True))


class EighthActivity(AbstractBaseEighthModel):
    """Represents an eighth period activity.

    Attributes:
        name
            The name of the activity, max length 100 characters.
        description
            The description of the activity, shown on the signup page below the other information.
            Information on an EighthScheduledActivity basis can be found in the "comments" field
            of that model. Max length 2000 characters.
        sponsors
            The default activity-level sponsors for the activity. On an EighthScheduledActivity basis,
            you should NOT query this field. Use scheduled_activity.get_true_sponsors()
        rooms
            The default activity-level rooms for the activity. On an EighthScheduledActivity basis,
            you should NOT query this field. Use scheduled_activity.get_true_rooms()
        default_capacity
            The default capacity, which overrides the sum of the default rooms when scheduling the
            activity. By default, this has a null value and is ignored.
        presign
            If True, the activity can only be signed up for within 48 hours of the day that the activity
            is scheduled.
        one_a_day
            If True, a student can only sign up for one instance of this activity per day.
        both_blocks
            If True, a signup for an EighthScheduledActivity during an A or B block will enforce and
            automatically trigger a signup on the other block. Does not enforce signups for blocks other
            than A and B.
        sticky
            If True, then students who sign up or are placed in this activity cannot switch out of it.
            A sticky activity should also be restricted, unless you're mean.
        special
            If True, then the activity receives a special designation on the signup list, and is stuck
            to the top of the list.
        administrative
            If True, then students cannot see the activity in their signup list. However, the activity still
            exists in the system and can be seen by administrators. Students can still sign up for the activity
            through the API -- this does not prevent students from signing up for it, and just merely hides it
            from view. An administrative activity should be restricted.
        finance
            If True, then the club has an account with the finance office.
        users_allowed
            Individual users allowed to sign up for this activity. Extensive use of this is discouraged; make
            a group instead through the "Add and Assign Empty Group" button on the Edit Activity page. Only
            takes effect if the activity is restricted.
        groups_allowed
            Individual groups allowed to sign up for this activity. Only takes effect if the activity is
            restricted.
        users_blacklisted
            Individual users who are not allowed to sign up for this activity. Only takes effect if the activity
            is not restricted.
        freshman_allowed, sophomores_allowed, juniors_allowed, seniors_allowed
            Whether Freshman/Sophomores/Juniors/Seniors are allowed to sign up for this activity. Only
            takes effect if the activity is restricted.
        wed_a, wed_b, fri_a, fri_b
            What blocks the activity usually meets. Does not affect schedule, is just information for the Eighth Office.
        admin_comments
            Notes for the Eighth Office
        favorites
            A ManyToManyField of User objects who have favorited the activity.
        deleted
            Whether the activity still technically exists in the system, but was marked to be deleted.

    """
    objects = models.Manager()
    undeleted_objects = EighthActivityExcludeDeletedManager()

    name = models.CharField(max_length=100)  # This should really be unique
    description = models.CharField(max_length=2000, blank=True)
    sponsors = models.ManyToManyField(EighthSponsor, blank=True)
    rooms = models.ManyToManyField(EighthRoom, blank=True)
    default_capacity = models.SmallIntegerField(null=True, blank=True)

    presign = models.BooleanField(default=False)
    one_a_day = models.BooleanField(default=False)
    both_blocks = models.BooleanField(default=False)
    sticky = models.BooleanField(default=False)
    special = models.BooleanField(default=False)
    administrative = models.BooleanField(default=False)
    finance = models.CharField(max_length=100, blank=True, null=True)

    restricted = models.BooleanField(default=False)

    users_allowed = models.ManyToManyField(User, related_name="restricted_activity_set", blank=True)
    groups_allowed = models.ManyToManyField(DjangoGroup, related_name="restricted_activity_set", blank=True)

    users_blacklisted = models.ManyToManyField(User, blank=True)

    freshmen_allowed = models.BooleanField(default=False)
    sophomores_allowed = models.BooleanField(default=False)
    juniors_allowed = models.BooleanField(default=False)
    seniors_allowed = models.BooleanField(default=False)

    wed_a = models.BooleanField("Meets Wednesday A", default=False)
    wed_b = models.BooleanField("Meets Wednesday B", default=False)
    fri_a = models.BooleanField("Meets Friday A", default=False)
    fri_b = models.BooleanField("Meets Friday B", default=False)

    admin_comments = models.CharField(max_length=1000, blank=True)

intranet/templates/itemreg/home.html
{% extends "page_with_nav.html" %}
{% load static %}
{% load dates %}
{% load pipeline %}

{% block title %}
  {{ block.super }} - Item Registration
{% endblock %}

{% block js %}
  {{ block.super }}
{% endblock %}

{% block css %}
  {{ block.super }}
  {% stylesheet 'lostfound' %}
  <style type="text/css">
  ul.fontawesome {
    list-style-type: none;
  }

  ul.fontawesome li:before {
    font-family: FontAwesome;
    display: inline-block;
    margin-left: -1.5em;
    width: 1.0em;
    font-size: 14px;
  }

  ul.fontawesome li.calc:before {
    content: "\f1ec"; /* fa-calculator */
  }

  ul.fontawesome li.comp:before {
    content: "\f109"; /* fa-laptop */
  }

  ul.fontawesome li.phone:before {
    content: "\f10b"; /* fa-mobile */
  }
</style>
{% endblock %}

{% block main %}
<div class="lostfound primary-content">
  <h2>
    Item Registration
  </h2>

  <p>
    Registering your calculator, computer, and phone through Intranet helps staff members return your device if it is found.
  </p>

  {% if request.user.is_teacher or is_itemreg_admin %}
    <p>Staff -- if you've found a lost item, <b>use this tool to check the item registration database:</b>
    <br />
    <a href="{% url 'itemreg_search' %}" class="button">
      Search Database
    </a>
  {% endif %}

  {% if registered_devices %}
    <p>You've registered the following devices:</p>
    <ul class="fontawesome">
    {% for calc in calculators %}
      <li class="calc">
        <b>Calculator:</b> {{ calc.calc_name }}
        <br />
        Serial: {{ calc.calc_serial }}
        <br />
        ID: {{ calc.calc_id }}
        <br />
        Added: {{ calc.added }}
        <br />
        <a href="{% url 'itemreg_delete' 'calculator' calc.id %}">
          <i class="fa fa-trash-o"></i> Delete
        </a>
        <br />
        <br />
      </li>
    {% endfor %}

    {% for comp in computers %}
      <li class="comp">
        <b>Computer:</b> {{ comp.computer_name }}
        <br />
        Serial: {{ comp.serial }}
        <br />
        Added: {{ comp.added }}
        <br />
        <a href="{% url 'itemreg_delete' 'computer' comp.id %}">
          <i class="fa fa-trash-o"></i> Delete
        </a>
        <br />
        <br />
      </li>
    {% endfor %}

    {% for phone in phones %}
      <li class="phone">
        <b>Phone:</b> {{ phone.manufacturer_name }} {{ phone.model }}
        <br />
        Serial: {{ phone.serial }}
        <br />
        Added: {{ phone.added }}
        <br />
        <a href="{% url 'itemreg_delete' 'phone' phone.id %}">
          <i class="fa fa-trash-o"></i> Delete
        </a>
        <br />
        <br />
      </li>
    {% endfor %}
    </ul>
  {% else %}
    <p>You haven't registered any devices! Register a device using the buttons below.</p>
  {% endif %}
  <br />

  <a href="{% url 'itemreg_calculator' %}" class="button">
    Register Calculator
  </a> &nbsp; &nbsp;
  <a href="{% url 'itemreg_computer' %}" class="button">
    Register Computer
  </a> &nbsp; &nbsp;
  <a href="{% url 'itemreg_phone' %}" class="button">
    Register Phone
  </a>
{% endblock %}

intranet/templates/itemreg/item_view.html
{% extends "page_with_nav.html" %}
{% load static %}
{% load dates %}
{% load pipeline %}

{% block title %}
    {{ block.super }} - View {{ type|capfirst }} Item
{% endblock %}

{% block js %}
    {{ block.super }}
{% endblock %}

{% block css %}
    {{ block.super }}
    {% stylesheet 'lostfound' %}
{% endblock %}

{% block main %}
<div class="lostitem primary-content">
    <a href="{% url 'itemreg' %}" class="button">
        <i class="fa fa-arrow-left"></i> View All Items
    </a>
    <h2>
        View {{ type|capfirst }} Item
    </h2>
    {% include "itemreg/lostitem.html" %}

</div>
{% endblock %}

intranet/templates/itemreg/register_delete.html
{% extends "page_with_nav.html" %}
{% load static %}
{% load dates %}
{% load pipeline %}

{% block title %}
    {{ block.super }} - Delete {{ type|title }}
{% endblock %}

{% block js %}
    {{ block.super }}
{% endblock %}

{% block css %}
    {{ block.super }}
{% endblock %}

{% block main %}
<div class="lostitem primary-content">
    <a href="{% url 'itemreg' %}" class="button">
        <i class="fa fa-arrow-left"></i> Item Registration
    </a>
    <h2>
        Delete {{ type|title }}
    </h2>
    <br />
    
    <b>Are you sure you want to delete {{ obj }}?</b>
    <form method="post" action="">
        {% csrf_token %}
        <input type="hidden" name="confirm" value="1" />
        <a href="{% url 'itemreg' %}" class="button">Cancel</a> &nbsp; 
        <input type="submit" value="Delete" />
    </form>

    </form>
</div>
{% endblock %}

intranet/templates/itemreg/search.html
{% extends "page_with_nav.html" %}
{% load static %}
{% load dates %}
{% load pipeline %}
{% load texthighlight %}

{% block title %}
    {{ block.super }} - Lost and Found
{% endblock %}

{% block js %}
    {{ block.super }}
{% endblock %}

{% block css %}
    {{ block.super }}
    {% stylesheet 'lostfound' %}
    <style type="text/css">
    .errorlist {
        display: none;
    }

    label[for="id_description"],
    #id_description {
        display: none;
    }

    .item-search {
        width: 100%;
    }

    .item-search > tr > td {
        vertical-align: top;
    }

    .helptext {
        display: none;
    }

    </style>
{% endblock %}

{% block main %}
<div class="lostfound primary-content">
    <a href="{% url 'itemreg' %}" class="button">
        <i class="fa fa-arrow-left"></i> Item Registration
    </a>
    <h2>
        Item Search
    </h2>
    
    <br />

    <table class="item-search">
        <tr>
        <td>
            <form action="{% url 'itemreg_search' %}" method="get">
                <div style="font-size: 16px">Find Calculator:</div>
                <input type="hidden" name="type" value="calculator" />
                <table>
                {{ calc_form }}
                <tr><td><input type="submit" value="Search" /></td></tr>
                </table>
            </form>
            <br />
            <form action="{% url 'itemreg_search' %}" method="get">
                <div style="font-size: 16px">Find By User:</div>
                <input type="hidden" name="type" value="all" />
                <input type="text" name="user" value="" placeholder="Enter ID or name" />
                &nbsp; <input type="submit" value="Search" />
            </form>
        </td>
        <td>
            <form action="{% url 'itemreg_search' %}" method="get">
                <div style="font-size: 16px">Find Computer:</div>
                <input type="hidden" name="type" value="computer" />
                <table>
                {{ comp_form }}
                <tr><td><input type="submit" value="Search" /></td></tr>
                </table>
            </form>
        </td>
        <td>
            <form action="{% url 'itemreg_search' %}" method="get">
                <div style="font-size: 16px">Find Phone:</div>
                <input type="hidden" name="type" value="phone" />
                <table>
                {{ phone_form }}
                <tr><td><input type="submit" value="Search" /></td></tr>
                </table>
            </form>
        </td>
        </tr>
    </table>

    <br />

    {% if results.calculator %}
    <br />
    <div style="font-size: 16px">Calculators Matched:</div>
    <table class="fancy-table" style="width: 100%">
        <thead>
            <tr>
                <th>User</th>
                <th>Type</th>
                <th>Serial</th>
                <th>ID</th>
                <th>Added</th>
            </tr>
        </thead>
        <tbody>
        {% for c in results.calculator %}
        <tr>
            <td><a href="{% url 'user_profile' c.user.id %}">{{ c.user.full_name }}</a></td>
            <td>{{ c.calc_name }}</td>
            <td>{{ c.calc_serial|highlight:getargs.calc_serial|safe }}</td>
            <td>{{ c.calc_id|highlight:getargs.calc_id|safe }}</td>
            <td>{{ c.added }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    {% endif %}
    {% if results.computer %}
    <br />
    <div style="font-size: 16px">Computers Matched:</div>
    <table class="fancy-table" style="width: 100%">
        <thead>
            <tr>
                <th>User</th>
                <th>Manufacturer</th>
                <th>Model</th>
                <th>Screen Size</th>
                <th>Serial</th>
                <th>Description</th>
                <th>Added</th>
            </tr>
        </thead>
        <tbody>
        {% for c in results.computer %}
        <tr>
            <td><a href="{% url 'user_profile' c.user.id %}">{{ c.user.full_name }}</a></td>
            <td>{{ c.manuf_name|highlight:getargs.manufacturer|safe }}</td>
            <td>{{ c.model|highlight:getargs.model|safe }}</td>
            <td>{{ c.screen_size|highlight:getargs.screen_size|safe }}</td>
            <td>{{ c.serial|highlight:getargs.serial|safe }}</td>
            <td>{{ c.description|highlight:getargs.description|safe }}</td>
            <td>{{ c.added }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    {% endif %}
    {% if results.phone %}
    <br />
    <div style="font-size: 16px">Phones Matched:</div>
    <table class="fancy-table" style="width: 100%">
        <thead>
            <tr>
                <th>User</th>
                <th>Manufacturer</th>
                <th>Model</th>
                <th>Serial</th>
                <th>Description</th>
                <th>Added</th>
            </tr>
        </thead>
        <tbody>
        {% for c in results.phone %}
        <tr>
            <td><a href="{% url 'user_profile' c.user.id %}">{{ c.user.full_name }}</a></td>
            <td>{{ c.manuf_name|highlight:getargs.manufacturer|safe }}</td>
            <td>{{ c.model|highlight:getargs.model|safe }}</td>
            <td>{{ c.serial|highlight:getargs.serial|safe }}</td>
            <td>{{ c.description|highlight:getargs.description|safe }}</td>
            <td>{{ c.added }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    {% endif %}
    {% if no_results %}
        No results. Enter search criteria above, or hit the button below each category to display all entires of that type.
    {% endif %}

</div>
{% endblock %}